#!/bin/sh

set -eu

psql -v ON_ERROR_STOP=1 -U $POSTGRES_USER <<-EOF
CREATE USER kit;
ALTER USER kit WITH SUPERUSER;
ALTER USER kit PASSWORD 'kit';
CREATE DATABASE kit;
GRANT ALL PRIVILEGES ON DATABASE kit TO kit;
CREATE DATABASE kit_test;
GRANT ALL PRIVILEGES ON DATABASE kit_test TO kit;
EOF

psql -v ON_ERROR_STOP=1 -U $POSTGRES_USER -d kit <<-EOF
ALTER SCHEMA public OWNER TO kit;
GRANT ALL ON SCHEMA public TO kit;
EOF

psql -v ON_ERROR_STOP=1 -U $POSTGRES_USER -d kit_test <<-EOF
ALTER SCHEMA public OWNER TO kit;
GRANT ALL ON SCHEMA public TO kit;
EOF

