apiVersion: 1
deleteDatasources:
  - name: "Tempo"
datasources:
  - name: "Tempo"
    type: "tempo"
    access: "proxy"
    url: "http://tempo:3200"
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
